export const DONATOR_TYPES = {
  GET_UNVERIFIED_DONATOR: 'GET_UNVERIFIED_DONATOR',
  GET_VERIFIED_DONATOR: 'GET_VERIFIED_DONATOR',
  CHANGE_STATUS: 'CHANGE_STATUS',
  DELETE_DONATOR: 'DELETE_DONATOR'
}