export const EVENT_TYPES = {
  CREATE_EVENT: 'CREATE_EVENT',
  GET_EVENT: 'GET_EVENT',
  REGISTER_EVENT: 'REGISTER_EVENT',
  GET_EVENT_BY_USER: 'GET_EVENT_BY_USER',
  GET_HOME_EVENT: 'GET_HOME_EVENT',
  GET_EVENT_BY_DONATOR: 'GET_EVENT_BY_DONATOR',
  DELETE_EVENT: 'DELETE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT'
}